export const RANDOM_PHOTOS_COUNT = 9

export const program = [
  {
    dayTitle: '28th January',
    talks: [
      { time: '8:00', title: 'Linear Congruence Systems', speaker: 'Jason Wu', room: 'B12' },
      { time: '8:00', title: 'Functional Reactivity', speaker: 'Linnea Svendsen', room: 'A02' },
      {
        time: '8:00',
        title: 'Advancements in Embedded Systems',
        speaker: 'Sophia Nguyen',
        room: 'C01',
      },
      { time: '8:00', title: 'Optimizing SQL Queries', speaker: 'Raj Patel', room: 'D15' },
      {
        time: '10:00',
        title: 'Machine Learning Interpretability',
        speaker: 'Elena Garcia',
        room: 'B12',
      },
      { time: '10:00', title: 'Introduction to GraphQL', speaker: 'Marta Kowalska', room: 'A02' },
      { time: '10:00', title: 'Design Patterns for IoT', speaker: 'Ahmed Al-Farsi', room: 'C01' },
      {
        time: '10:00',
        title: 'Asynchronous JavaScript Deep Dive',
        speaker: 'Lucas Schmidt',
        room: 'D15',
      },
      {
        time: '13:00',
        title: 'Cryptography in the Age of AI',
        speaker: 'Hana Takahashi',
        room: 'B12',
      },
      {
        time: '13:00',
        title: 'REST vs. gRPC: The API Showdown',
        speaker: "David O'Connell",
        room: 'A02',
      },
      {
        time: '13:00',
        title: 'Concurrency Challenges in Embedded C',
        speaker: 'Emma Svensson',
        room: 'C01',
      },
      {
        time: '13:00',
        title: 'Building Scalable Microservices',
        speaker: 'Fernando Torres',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Big-O Complexity Demystified',
        speaker: 'Anna Johansson',
        room: 'B12',
      },
      {
        time: '15:00',
        title: 'Deploying Applications with Docker',
        speaker: 'Carlos Mendes',
        room: 'A02',
      },
      {
        time: '15:00',
        title: 'Understanding Blockchain Protocols',
        speaker: 'Liam Murphy',
        room: 'C01',
      },
      { time: '15:00', title: 'Securing IoT Devices', speaker: 'Fatima Ahmed', room: 'D15' },
    ],
  },
  {
    dayTitle: '29th January',
    talks: [
      {
        time: '8:00',
        title: 'Quantum Algorithms and Applications',
        speaker: 'Peter Muller',
        room: 'B12',
      },
      { time: '8:00', title: 'State Management in React', speaker: 'Iris Kang', room: 'A02' },
      { time: '8:00', title: 'Low-Power Circuit Design', speaker: 'Maxim Orlov', room: 'C01' },
      { time: '8:00', title: 'Data-Driven Web Design', speaker: 'Natalie Becker', room: 'D15' },
      {
        time: '10:00',
        title: 'Introduction to Rust Programming',
        speaker: 'Samuel Fischer',
        room: 'B12',
      },
      { time: '10:00', title: 'CSS-in-JS: Pros and Cons', speaker: 'Emily Green', room: 'A02' },
      {
        time: '10:00',
        title: 'Middleware in Embedded Systems',
        speaker: 'Hassan Ali',
        room: 'C01',
      },
      {
        time: '10:00',
        title: 'Continuous Integration in Practice',
        speaker: 'Julia Perez',
        room: 'D15',
      },
      { time: '13:00', title: 'AI-Driven Optimization', speaker: 'Victor Silva', room: 'B12' },
      {
        time: '13:00',
        title: 'Modern Web Accessibility Standards',
        speaker: 'Anna Petrova',
        room: 'A02',
      },
      {
        time: '13:00',
        title: 'Multi-Core Programming Paradigms',
        speaker: 'Tobias Weber',
        room: 'C01',
      },
      {
        time: '13:00',
        title: 'Serverless Architecture Explained',
        speaker: 'Monica Singh',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Prolog for Logical Problem Solving',
        speaker: 'Olga Ivanova',
        room: 'B12',
      },
      { time: '15:00', title: 'Web Security Best Practices', speaker: 'Jacob Brown', room: 'A02' },
      { time: '15:00', title: 'Energy Harvesting in IoT', speaker: 'Mehmet Kaya', room: 'C01' },
      { time: '15:00', title: 'Scaling NoSQL Databases', speaker: 'Priya Sharma', room: 'D15' },
    ],
  },
  {
    dayTitle: '30th January',
    talks: [
      { time: '8:00', title: 'The Future of AI Chips', speaker: 'Clara Davis', room: 'B12' },
      { time: '8:00', title: 'Debugging Distributed Systems', speaker: 'Ethan Kim', room: 'A02' },
      { time: '8:00', title: 'Java Streams: A Deep Dive', speaker: 'Francesco Rossi', room: 'C01' },
      { time: '8:00', title: 'Building a Progressive Web App', speaker: 'Sara Lopez', room: 'D15' },
      {
        time: '10:00',
        title: 'Real-Time OS for Embedded Systems',
        speaker: 'Tommy Ho',
        room: 'B12',
      },
      {
        time: '10:00',
        title: 'Server-Side Rendering with Next.js',
        speaker: 'Emily Hart',
        room: 'A02',
      },
      { time: '10:00', title: 'IoT Security and the Cloud', speaker: 'Jamal Karim', room: 'C01' },
      { time: '10:00', title: 'Implementing LRU Caching', speaker: 'Zara Singh', room: 'D15' },
      {
        time: '13:00',
        title: 'Graph Databases in Action',
        speaker: 'Lucas Schneider',
        room: 'B12',
      },
      { time: '13:00', title: 'Web Components and the DOM', speaker: 'Fiona MacLeod', room: 'A02' },
      { time: '13:00', title: 'Sensor Fusion Algorithms', speaker: 'Muhammad Shah', room: 'C01' },
      {
        time: '13:00',
        title: 'The Rise of Functional Programming',
        speaker: 'Oliver White',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Exploring Generative AI Models',
        speaker: 'Victoria Gomez',
        room: 'B12',
      },
      { time: '15:00', title: 'Testing Strategies for APIs', speaker: 'Mateo Silva', room: 'A02' },
      { time: '15:00', title: 'Building a Digital Twin', speaker: 'Isla Murray', room: 'C01' },
      { time: '15:00', title: 'Designing Modular Systems', speaker: 'Liam Carter', room: 'D15' },
    ],
  },
  {
    dayTitle: '31st January',
    talks: [
      { time: '8:00', title: 'Parallelism in Modern CPUs', speaker: 'Sophia Allen', room: 'B12' },
      {
        time: '8:00',
        title: 'Data Ethics in Machine Learning',
        speaker: 'Daniel Huang',
        room: 'A02',
      },
      {
        time: '8:00',
        title: 'Evolution of Frontend Frameworks',
        speaker: 'Chloe Chen',
        room: 'C01',
      },
      { time: '8:00', title: 'Optimizing Embedded Linux', speaker: 'Theo Moreau', room: 'D15' },
      { time: '10:00', title: 'Deep Learning with PyTorch', speaker: 'Isabella Wang', room: 'B12' },
      { time: '10:00', title: 'WebAssembly Applications', speaker: 'Lukas Maier', room: 'A02' },
      { time: '10:00', title: 'Power Management in IoT', speaker: 'Mariam Khan', room: 'C01' },
      {
        time: '10:00',
        title: 'Cloud-Native CI/CD Pipelines',
        speaker: 'Adrian Silva',
        room: 'D15',
      },
      { time: '13:00', title: 'Digital Privacy in 2024', speaker: 'Camila Gomez', room: 'B12' },
      { time: '13:00', title: 'AI-Generated Art and Ethics', speaker: 'Noah Fischer', room: 'A02' },
      { time: '13:00', title: 'Real-Time Sensor Networks', speaker: 'Ella Svensson', room: 'C01' },
      {
        time: '13:00',
        title: 'Monolith to Microservices Migration',
        speaker: 'Youssef Ali',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Container Orchestration with Kubernetes',
        speaker: 'Amelia Rossi',
        room: 'B12',
      },
      {
        time: '15:00',
        title: 'Advanced TypeScript Features',
        speaker: 'Hugo Moreira',
        room: 'A02',
      },
      { time: '15:00', title: '5G Networks for IoT', speaker: 'Leah Kim', room: 'C01' },
      { time: '15:00', title: 'Debugging Multi-Threaded Code', speaker: 'Jack Weber', room: 'D15' },
    ],
  },
  {
    dayTitle: '1st February',
    talks: [
      { time: '8:00', title: 'Practical Use of Graph Theory', speaker: 'Alice Rossi', room: 'B12' },
      {
        time: '8:00',
        title: 'SEO for Single-Page Applications',
        speaker: 'Diego Alvarez',
        room: 'A02',
      },
      { time: '8:00', title: 'Real-Time Data Processing', speaker: 'Felix Schulz', room: 'C01' },
      { time: '8:00', title: 'Reactive Programming Basics', speaker: 'Amara Gupta', room: 'D15' },
      {
        time: '10:00',
        title: 'Advanced Neural Network Design',
        speaker: 'Ella Turner',
        room: 'B12',
      },
      {
        time: '10:00',
        title: 'Optimizing React Applications',
        speaker: 'Jonas Becker',
        room: 'A02',
      },
      { time: '10:00', title: 'IoT in Healthcare', speaker: 'Mia Novak', room: 'C01' },
      {
        time: '10:00',
        title: 'Database Indexing Explained',
        speaker: 'Ethan Johnson',
        room: 'D15',
      },
      {
        time: '13:00',
        title: 'Predictive Analytics Tools',
        speaker: 'William Martinez',
        room: 'B12',
      },
      { time: '13:00', title: 'Improving API Performance', speaker: 'Layla Thomas', room: 'A02' },
      { time: '13:00', title: 'Cybersecurity for IoT', speaker: 'Ahmed Said', room: 'C01' },
      {
        time: '13:00',
        title: 'Deep Dive into Kafka Streams',
        speaker: 'Marta Kaczmarek',
        room: 'D15',
      },
      { time: '15:00', title: 'The Future of WebAssembly', speaker: 'Olivia Peters', room: 'B12' },
      { time: '15:00', title: 'Building Resilient Systems', speaker: 'Sophia Clark', room: 'A02' },
      { time: '15:00', title: 'AI in Robotics', speaker: 'Liam Garcia', room: 'C01' },
      {
        time: '15:00',
        title: 'Performance Tuning in Java',
        speaker: 'Charlotte Chen',
        room: 'D15',
      },
    ],
  },
]

export const speakers = [
  { name: 'Jason Wu', bio: 'Expert in computational mathematics and algorithms.', country: '🇺🇸' },
  {
    name: 'Linnea Svendsen',
    bio: 'Software engineer specializing in functional programming.',
    country: '🇸🇪',
  },
  {
    name: 'Sophia Nguyen',
    bio: 'Embedded systems engineer focusing on optimization.',
    country: '🇻🇳',
  },
  {
    name: 'Raj Patel',
    bio: 'Database administrator and SQL optimization expert.',
    country: '🇮🇳',
  },
  { name: 'Elena Garcia', bio: 'Data scientist specializing in explainable AI.', country: '🇪🇸' },
  {
    name: 'Marta Kowalska',
    bio: 'API technologies expert, focusing on GraphQL.',
    country: '🇵🇱',
  },
  {
    name: 'Ahmed Al-Farsi',
    bio: 'IoT architect creating secure, scalable solutions.',
    country: '🇴🇲',
  },
  {
    name: 'Lucas Schmidt',
    bio: 'Front-end developer and JavaScript specialist.',
    country: '🇩🇪',
  },
  {
    name: 'Hana Takahashi',
    bio: 'Cryptographer exploring AI and cybersecurity.',
    country: '🇯🇵',
  },
  {
    name: "David O'Connell",
    bio: 'API developer with expertise in REST and gRPC.',
    country: '🇮🇪',
  },
  {
    name: 'Emma Svensson',
    bio: 'Embedded C developer working on real-time systems.',
    country: '🇸🇪',
  },
  {
    name: 'Fernando Torres',
    bio: 'Cloud architect specializing in microservices.',
    country: '🇧🇷',
  },
  {
    name: 'Anna Johansson',
    bio: 'Computer scientist teaching algorithms and complexity.',
    country: '🇸🇪',
  },
  {
    name: 'Carlos Mendes',
    bio: 'DevOps engineer focusing on containerized apps.',
    country: '🇵🇹',
  },
  {
    name: 'Liam Murphy',
    bio: 'Blockchain engineer developing decentralized apps.',
    country: '🇺🇸',
  },
  { name: 'Fatima Ahmed', bio: 'IoT security expert securing smart devices.', country: '🇬🇧' },
  { name: 'Peter Muller', bio: 'Quantum computing researcher and developer.', country: '🇩🇪' },
  {
    name: 'Iris Kang',
    bio: 'React developer specializing in state management.',
    country: '🇰🇷',
  },
  {
    name: 'Maxim Orlov',
    bio: 'Electrical engineer and circuit design specialist.',
    country: '🇷🇺',
  },
  {
    name: 'Natalie Becker',
    bio: 'UX/UI designer focusing on user-centric designs.',
    country: '🇩🇪',
  },
  {
    name: 'Samuel Fischer',
    bio: 'Systems programmer and Rust community contributor.',
    country: '🇺🇸',
  },
  {
    name: 'Emily Green',
    bio: 'Front-end engineer exploring CSS-in-JS solutions.',
    country: '🇦🇺',
  },
  { name: 'Hassan Ali', bio: 'Middleware developer for embedded systems.', country: '🇵🇰' },
  { name: 'Julia Perez', bio: 'DevOps engineer advocating CI/CD practices.', country: '🇲🇽' },
  {
    name: 'Victor Silva',
    bio: 'AI specialist optimizing machine learning models.',
    country: '🇵🇹',
  },
  {
    name: 'Anna Petrova',
    bio: 'Web accessibility and inclusive design expert.',
    country: '🇷🇺',
  },
  {
    name: 'Tobias Weber',
    bio: 'Systems engineer specializing in parallel computing.',
    country: '🇩🇪',
  },
  {
    name: 'Monica Singh',
    bio: 'Cloud architect and serverless computing advocate.',
    country: '🇮🇳',
  },
  {
    name: 'Olga Ivanova',
    bio: 'Logic programming expert specializing in Prolog.',
    country: '🇺🇦',
  },
  { name: 'Jacob Brown', bio: 'Web security expert building secure applications.', country: '🇺🇸' },
  {
    name: 'Mehmet Kaya',
    bio: 'Embedded systems engineer in energy harvesting.',
    country: '🇹🇷',
  },
  {
    name: 'Priya Sharma',
    bio: 'Database architect specializing in NoSQL solutions.',
    country: '🇮🇳',
  },
  { name: 'Clara Davis', bio: 'AI chip designer optimizing edge computing.', country: '🇺🇸' },
  {
    name: 'Ethan Kim',
    bio: 'Distributed systems expert and debugging specialist.',
    country: '🇰🇷',
  },
  {
    name: 'Francesco Rossi',
    bio: 'Senior Java developer and Streams API expert.',
    country: '🇮🇹',
  },
  { name: 'Sara Lopez', bio: 'Progressive web app developer and optimizer.', country: '🇪🇸' },
  { name: 'Tommy Ho', bio: 'Embedded systems expert in real-time OS design.', country: '🇻🇳' },
  { name: 'Emily Hart', bio: 'Front-end developer specializing in Next.js.', country: '🇺🇸' },
  {
    name: 'Jamal Karim',
    bio: 'IoT security expert focusing on cloud protection.',
    country: '🇯🇴',
  },
  {
    name: 'Zara Singh',
    bio: 'Performance engineer optimizing caching strategies.',
    country: '🇮🇳',
  },
  {
    name: 'Lucas Schneider',
    bio: 'Graph database specialist and software architect.',
    country: '🇩🇪',
  },
  {
    name: 'Fiona MacLeod',
    bio: 'Cybersecurity analyst focusing on threat modeling.',
    country: '🏴',
  },
  {
    name: 'Muhammad Shah',
    bio: 'AI researcher specializing in natural language processing.',
    country: '🇵🇰',
  },
  { name: 'Oliver White', bio: 'Cloud infrastructure engineer.', country: '🇦🇺' },
  { name: 'Victoria Gomez', bio: 'Big data analyst.', country: '🇦🇷' },
  { name: 'Mateo Silva', bio: 'Robotics engineer.', country: '🇧🇷' },
  {
    name: 'Isla Murray',
    bio: 'Technical writer specializing in developer documentation.',
    country: '🇮🇪',
  },
  { name: 'Liam Carter', bio: 'AI ethics researcher.', country: '🇨🇦' },
  { name: 'Sophia Allen', bio: 'Augmented reality developer.', country: '🇬🇧' },
  { name: 'Daniel Huang', bio: 'Computer vision specialist.', country: '🇨🇳' },
  { name: 'Chloe Chen', bio: 'Cloud DevOps engineer.', country: '🇹🇼' },
  { name: 'Theo Moreau', bio: 'Data visualization expert.', country: '🇫🇷' },
  { name: 'Isabella Wang', bio: 'Quantum mechanics researcher.', country: '🇸🇬' },
  { name: 'Lukas Maier', bio: 'Virtual reality designer.', country: '🇩🇪' },
  { name: 'Mariam Khan', bio: 'AI-driven healthcare innovator.', country: '🇵🇰' },
  { name: 'Adrian Silva', bio: 'Blockchain entrepreneur.', country: '🇵🇹' },
  { name: 'Camila Gomez', bio: 'Front-end designer.', country: '🇨🇴' },
  { name: 'Noah Fischer', bio: 'Game theory analyst.', country: '🇺🇸' },
  { name: 'Ella Svensson', bio: 'Climate tech engineer.', country: '🇸🇪' },
  { name: 'Youssef Ali', bio: 'Automation engineer.', country: '🇪🇬' },
  { name: 'Amelia Rossi', bio: 'Bioinformatics researcher.', country: '🇮🇹' },
  { name: 'Hugo Moreira', bio: 'Space systems architect.', country: '🇵🇹' },
  { name: 'Leah Kim', bio: 'Renewable energy systems developer.', country: '🇰🇷' },
  { name: 'Jack Weber', bio: 'AI for gaming.', country: '🇺🇸' },
  { name: 'Alice Rossi', bio: 'Education tech innovator.', country: '🇮🇹' },
  { name: 'Diego Alvarez', bio: 'Natural language processor.', country: '🇲🇽' },
  { name: 'Felix Schulz', bio: 'HPC specialist.', country: '🇩🇪' },
  { name: 'Amara Gupta', bio: 'Ethics in AI researcher.', country: '🇮🇳' },
  { name: 'Ella Turner', bio: 'Web3 developer.', country: '🇬🇧' },
  { name: 'Jonas Becker', bio: 'Edge computing developer.', country: '🇩🇪' },
  { name: 'Mia Novak', bio: 'Data ethics advocate.', country: '🇭🇷' },
  { name: 'Ethan Johnson', bio: 'Green computing developer.', country: '🇺🇸' },
  { name: 'William Martinez', bio: 'IoT firmware developer.', country: '🇨🇱' },
  { name: 'Layla Thomas', bio: 'Interactive media specialist.', country: '🇨🇦' },
  { name: 'Ahmed Said', bio: 'Data migration consultant.', country: '🇪🇬' },
  { name: 'Marta Kaczmarek', bio: 'Digital twins expert.', country: '🇵🇱' },
  { name: 'Olivia Peters', bio: 'Tech policy advisor.', country: '🇦🇺' },
  { name: 'Sophia Clark', bio: 'HCI researcher.', country: '🇺🇸' },
  { name: 'Liam Garcia', bio: 'AI for music.', country: '🇦🇷' },
  { name: 'Charlotte Chen', bio: 'Hardware design engineer.', country: '🇹🇼' },
].map((speaker, index) => ({
  ...speaker,
  photoPath: `/src/assets/images/profile-photo-${(index % RANDOM_PHOTOS_COUNT) + 1}.jpeg`,
}))
