export const program = [
  {
    dayTitle: '28th January',
    talks: [
      { time: '8:00', title: 'Linear Congruence Systems', speaker: 'Jason Wu', room: 'B12' },
      { time: '8:00', title: 'Functional Reactivity', speaker: 'Linnea Svendsen', room: 'A02' },
      {
        time: '8:00',
        title: 'Advancements in Embedded Systems',
        speaker: 'Sophia Nguyen',
        room: 'C01',
      },
      { time: '8:00', title: 'Optimizing SQL Queries', speaker: 'Raj Patel', room: 'D15' },
      {
        time: '10:00',
        title: 'Machine Learning Interpretability',
        speaker: 'Elena Garcia',
        room: 'B12',
      },
      { time: '10:00', title: 'Introduction to GraphQL', speaker: 'Marta Kowalska', room: 'A02' },
      { time: '10:00', title: 'Design Patterns for IoT', speaker: 'Ahmed Al-Farsi', room: 'C01' },
      {
        time: '10:00',
        title: 'Asynchronous JavaScript Deep Dive',
        speaker: 'Lucas Schmidt',
        room: 'D15',
      },
      {
        time: '13:00',
        title: 'Cryptography in the Age of AI',
        speaker: 'Hana Takahashi',
        room: 'B12',
      },
      {
        time: '13:00',
        title: 'REST vs. gRPC: The API Showdown',
        speaker: "David O'Connell",
        room: 'A02',
      },
      {
        time: '13:00',
        title: 'Concurrency Challenges in Embedded C',
        speaker: 'Emma Svensson',
        room: 'C01',
      },
      {
        time: '13:00',
        title: 'Building Scalable Microservices',
        speaker: 'Fernando Torres',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Big-O Complexity Demystified',
        speaker: 'Anna Johansson',
        room: 'B12',
      },
      {
        time: '15:00',
        title: 'Deploying Applications with Docker',
        speaker: 'Carlos Mendes',
        room: 'A02',
      },
      {
        time: '15:00',
        title: 'Understanding Blockchain Protocols',
        speaker: 'Liam Murphy',
        room: 'C01',
      },
      { time: '15:00', title: 'Securing IoT Devices', speaker: 'Fatima Ahmed', room: 'D15' },
    ],
  },
  {
    dayTitle: '29th January',
    talks: [
      {
        time: '8:00',
        title: 'Quantum Algorithms and Applications',
        speaker: 'Peter Muller',
        room: 'B12',
      },
      { time: '8:00', title: 'State Management in React', speaker: 'Iris Kang', room: 'A02' },
      { time: '8:00', title: 'Low-Power Circuit Design', speaker: 'Maxim Orlov', room: 'C01' },
      { time: '8:00', title: 'Data-Driven Web Design', speaker: 'Natalie Becker', room: 'D15' },
      {
        time: '10:00',
        title: 'Introduction to Rust Programming',
        speaker: 'Samuel Fischer',
        room: 'B12',
      },
      { time: '10:00', title: 'CSS-in-JS: Pros and Cons', speaker: 'Emily Green', room: 'A02' },
      {
        time: '10:00',
        title: 'Middleware in Embedded Systems',
        speaker: 'Hassan Ali',
        room: 'C01',
      },
      {
        time: '10:00',
        title: 'Continuous Integration in Practice',
        speaker: 'Julia Perez',
        room: 'D15',
      },
      { time: '13:00', title: 'AI-Driven Optimization', speaker: 'Victor Silva', room: 'B12' },
      {
        time: '13:00',
        title: 'Modern Web Accessibility Standards',
        speaker: 'Anna Petrova',
        room: 'A02',
      },
      {
        time: '13:00',
        title: 'Multi-Core Programming Paradigms',
        speaker: 'Tobias Weber',
        room: 'C01',
      },
      {
        time: '13:00',
        title: 'Serverless Architecture Explained',
        speaker: 'Monica Singh',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Prolog for Logical Problem Solving',
        speaker: 'Olga Ivanova',
        room: 'B12',
      },
      { time: '15:00', title: 'Web Security Best Practices', speaker: 'Jacob Brown', room: 'A02' },
      { time: '15:00', title: 'Energy Harvesting in IoT', speaker: 'Mehmet Kaya', room: 'C01' },
      { time: '15:00', title: 'Scaling NoSQL Databases', speaker: 'Priya Sharma', room: 'D15' },
    ],
  },
  {
    dayTitle: '30th January',
    talks: [
      { time: '8:00', title: 'The Future of AI Chips', speaker: 'Clara Davis', room: 'B12' },
      { time: '8:00', title: 'Debugging Distributed Systems', speaker: 'Ethan Kim', room: 'A02' },
      { time: '8:00', title: 'Java Streams: A Deep Dive', speaker: 'Francesco Rossi', room: 'C01' },
      { time: '8:00', title: 'Building a Progressive Web App', speaker: 'Sara Lopez', room: 'D15' },
      {
        time: '10:00',
        title: 'Real-Time OS for Embedded Systems',
        speaker: 'Tommy Ho',
        room: 'B12',
      },
      {
        time: '10:00',
        title: 'Server-Side Rendering with Next.js',
        speaker: 'Emily Hart',
        room: 'A02',
      },
      { time: '10:00', title: 'IoT Security and the Cloud', speaker: 'Jamal Karim', room: 'C01' },
      { time: '10:00', title: 'Implementing LRU Caching', speaker: 'Zara Singh', room: 'D15' },
      {
        time: '13:00',
        title: 'Graph Databases in Action',
        speaker: 'Lucas Schneider',
        room: 'B12',
      },
      { time: '13:00', title: 'Web Components and the DOM', speaker: 'Fiona MacLeod', room: 'A02' },
      { time: '13:00', title: 'Sensor Fusion Algorithms', speaker: 'Muhammad Shah', room: 'C01' },
      {
        time: '13:00',
        title: 'The Rise of Functional Programming',
        speaker: 'Oliver White',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Exploring Generative AI Models',
        speaker: 'Victoria Gomez',
        room: 'B12',
      },
      { time: '15:00', title: 'Testing Strategies for APIs', speaker: 'Mateo Silva', room: 'A02' },
      { time: '15:00', title: 'Building a Digital Twin', speaker: 'Isla Murray', room: 'C01' },
      { time: '15:00', title: 'Designing Modular Systems', speaker: 'Liam Carter', room: 'D15' },
    ],
  },
  {
    dayTitle: '31st January',
    talks: [
      { time: '8:00', title: 'Parallelism in Modern CPUs', speaker: 'Sophia Allen', room: 'B12' },
      {
        time: '8:00',
        title: 'Data Ethics in Machine Learning',
        speaker: 'Daniel Huang',
        room: 'A02',
      },
      {
        time: '8:00',
        title: 'Evolution of Frontend Frameworks',
        speaker: 'Chloe Chen',
        room: 'C01',
      },
      { time: '8:00', title: 'Optimizing Embedded Linux', speaker: 'Theo Moreau', room: 'D15' },
      { time: '10:00', title: 'Deep Learning with PyTorch', speaker: 'Isabella Wang', room: 'B12' },
      { time: '10:00', title: 'WebAssembly Applications', speaker: 'Lukas Maier', room: 'A02' },
      { time: '10:00', title: 'Power Management in IoT', speaker: 'Mariam Khan', room: 'C01' },
      {
        time: '10:00',
        title: 'Cloud-Native CI/CD Pipelines',
        speaker: 'Adrian Silva',
        room: 'D15',
      },
      { time: '13:00', title: 'Digital Privacy in 2024', speaker: 'Camila Gomez', room: 'B12' },
      { time: '13:00', title: 'AI-Generated Art and Ethics', speaker: 'Noah Fischer', room: 'A02' },
      { time: '13:00', title: 'Real-Time Sensor Networks', speaker: 'Ella Svensson', room: 'C01' },
      {
        time: '13:00',
        title: 'Monolith to Microservices Migration',
        speaker: 'Youssef Ali',
        room: 'D15',
      },
      {
        time: '15:00',
        title: 'Container Orchestration with Kubernetes',
        speaker: 'Amelia Rossi',
        room: 'B12',
      },
      {
        time: '15:00',
        title: 'Advanced TypeScript Features',
        speaker: 'Hugo Moreira',
        room: 'A02',
      },
      { time: '15:00', title: '5G Networks for IoT', speaker: 'Leah Kim', room: 'C01' },
      { time: '15:00', title: 'Debugging Multi-Threaded Code', speaker: 'Jack Weber', room: 'D15' },
    ],
  },
  {
    dayTitle: '1st February',
    talks: [
      { time: '8:00', title: 'Practical Use of Graph Theory', speaker: 'Alice Rossi', room: 'B12' },
      {
        time: '8:00',
        title: 'SEO for Single-Page Applications',
        speaker: 'Diego Alvarez',
        room: 'A02',
      },
      { time: '8:00', title: 'Real-Time Data Processing', speaker: 'Felix Schulz', room: 'C01' },
      { time: '8:00', title: 'Reactive Programming Basics', speaker: 'Amara Gupta', room: 'D15' },
      {
        time: '10:00',
        title: 'Advanced Neural Network Design',
        speaker: 'Ella Turner',
        room: 'B12',
      },
      {
        time: '10:00',
        title: 'Optimizing React Applications',
        speaker: 'Jonas Becker',
        room: 'A02',
      },
      { time: '10:00', title: 'IoT in Healthcare', speaker: 'Mia Novak', room: 'C01' },
      {
        time: '10:00',
        title: 'Database Indexing Explained',
        speaker: 'Ethan Johnson',
        room: 'D15',
      },
      {
        time: '13:00',
        title: 'Predictive Analytics Tools',
        speaker: 'William Martinez',
        room: 'B12',
      },
      { time: '13:00', title: 'Improving API Performance', speaker: 'Layla Thomas', room: 'A02' },
      { time: '13:00', title: 'Cybersecurity for IoT', speaker: 'Ahmed Said', room: 'C01' },
      {
        time: '13:00',
        title: 'Deep Dive into Kafka Streams',
        speaker: 'Marta Kaczmarek',
        room: 'D15',
      },
      { time: '15:00', title: 'The Future of WebAssembly', speaker: 'Olivia Peters', room: 'B12' },
      { time: '15:00', title: 'Building Resilient Systems', speaker: 'Sophia Clark', room: 'A02' },
      { time: '15:00', title: 'AI in Robotics', speaker: 'Liam Garcia', room: 'C01' },
      {
        time: '15:00',
        title: 'Performance Tuning in Java',
        speaker: 'Charlotte Chen',
        room: 'D15',
      },
    ],
  },
]
